package net.devtech.utilib.functions;
/**
* for LambdaMetaFactory things
*/
public interface GeneralFunction {
	void invokeVoid();
	void invokeVoid(boolean p0);
	void invokeVoid(boolean p0,boolean p1);
	void invokeVoid(boolean p0,byte p1);
	void invokeVoid(boolean p0,char p1);
	void invokeVoid(boolean p0,short p1);
	void invokeVoid(boolean p0,int p1);
	void invokeVoid(boolean p0,float p1);
	void invokeVoid(boolean p0,long p1);
	void invokeVoid(boolean p0,double p1);
	void invokeVoid(boolean p0,Object p1);
	void invokeVoid(byte p0);
	void invokeVoid(byte p0,boolean p1);
	void invokeVoid(byte p0,byte p1);
	void invokeVoid(byte p0,char p1);
	void invokeVoid(byte p0,short p1);
	void invokeVoid(byte p0,int p1);
	void invokeVoid(byte p0,float p1);
	void invokeVoid(byte p0,long p1);
	void invokeVoid(byte p0,double p1);
	void invokeVoid(byte p0,Object p1);
	void invokeVoid(char p0);
	void invokeVoid(char p0,boolean p1);
	void invokeVoid(char p0,byte p1);
	void invokeVoid(char p0,char p1);
	void invokeVoid(char p0,short p1);
	void invokeVoid(char p0,int p1);
	void invokeVoid(char p0,float p1);
	void invokeVoid(char p0,long p1);
	void invokeVoid(char p0,double p1);
	void invokeVoid(char p0,Object p1);
	void invokeVoid(short p0);
	void invokeVoid(short p0,boolean p1);
	void invokeVoid(short p0,byte p1);
	void invokeVoid(short p0,char p1);
	void invokeVoid(short p0,short p1);
	void invokeVoid(short p0,int p1);
	void invokeVoid(short p0,float p1);
	void invokeVoid(short p0,long p1);
	void invokeVoid(short p0,double p1);
	void invokeVoid(short p0,Object p1);
	void invokeVoid(int p0);
	void invokeVoid(int p0,boolean p1);
	void invokeVoid(int p0,byte p1);
	void invokeVoid(int p0,char p1);
	void invokeVoid(int p0,short p1);
	void invokeVoid(int p0,int p1);
	void invokeVoid(int p0,float p1);
	void invokeVoid(int p0,long p1);
	void invokeVoid(int p0,double p1);
	void invokeVoid(int p0,Object p1);
	void invokeVoid(float p0);
	void invokeVoid(float p0,boolean p1);
	void invokeVoid(float p0,byte p1);
	void invokeVoid(float p0,char p1);
	void invokeVoid(float p0,short p1);
	void invokeVoid(float p0,int p1);
	void invokeVoid(float p0,float p1);
	void invokeVoid(float p0,long p1);
	void invokeVoid(float p0,double p1);
	void invokeVoid(float p0,Object p1);
	void invokeVoid(long p0);
	void invokeVoid(long p0,boolean p1);
	void invokeVoid(long p0,byte p1);
	void invokeVoid(long p0,char p1);
	void invokeVoid(long p0,short p1);
	void invokeVoid(long p0,int p1);
	void invokeVoid(long p0,float p1);
	void invokeVoid(long p0,long p1);
	void invokeVoid(long p0,double p1);
	void invokeVoid(long p0,Object p1);
	void invokeVoid(double p0);
	void invokeVoid(double p0,boolean p1);
	void invokeVoid(double p0,byte p1);
	void invokeVoid(double p0,char p1);
	void invokeVoid(double p0,short p1);
	void invokeVoid(double p0,int p1);
	void invokeVoid(double p0,float p1);
	void invokeVoid(double p0,long p1);
	void invokeVoid(double p0,double p1);
	void invokeVoid(double p0,Object p1);
	void invokeVoid(Object p0);
	void invokeVoid(Object p0,boolean p1);
	void invokeVoid(Object p0,byte p1);
	void invokeVoid(Object p0,char p1);
	void invokeVoid(Object p0,short p1);
	void invokeVoid(Object p0,int p1);
	void invokeVoid(Object p0,float p1);
	void invokeVoid(Object p0,long p1);
	void invokeVoid(Object p0,double p1);
	void invokeVoid(Object p0,Object p1);
	boolean invokeBoolean();
	boolean invokeBoolean(boolean p0);
	boolean invokeBoolean(boolean p0,boolean p1);
	boolean invokeBoolean(boolean p0,byte p1);
	boolean invokeBoolean(boolean p0,char p1);
	boolean invokeBoolean(boolean p0,short p1);
	boolean invokeBoolean(boolean p0,int p1);
	boolean invokeBoolean(boolean p0,float p1);
	boolean invokeBoolean(boolean p0,long p1);
	boolean invokeBoolean(boolean p0,double p1);
	boolean invokeBoolean(boolean p0,Object p1);
	boolean invokeBoolean(byte p0);
	boolean invokeBoolean(byte p0,boolean p1);
	boolean invokeBoolean(byte p0,byte p1);
	boolean invokeBoolean(byte p0,char p1);
	boolean invokeBoolean(byte p0,short p1);
	boolean invokeBoolean(byte p0,int p1);
	boolean invokeBoolean(byte p0,float p1);
	boolean invokeBoolean(byte p0,long p1);
	boolean invokeBoolean(byte p0,double p1);
	boolean invokeBoolean(byte p0,Object p1);
	boolean invokeBoolean(char p0);
	boolean invokeBoolean(char p0,boolean p1);
	boolean invokeBoolean(char p0,byte p1);
	boolean invokeBoolean(char p0,char p1);
	boolean invokeBoolean(char p0,short p1);
	boolean invokeBoolean(char p0,int p1);
	boolean invokeBoolean(char p0,float p1);
	boolean invokeBoolean(char p0,long p1);
	boolean invokeBoolean(char p0,double p1);
	boolean invokeBoolean(char p0,Object p1);
	boolean invokeBoolean(short p0);
	boolean invokeBoolean(short p0,boolean p1);
	boolean invokeBoolean(short p0,byte p1);
	boolean invokeBoolean(short p0,char p1);
	boolean invokeBoolean(short p0,short p1);
	boolean invokeBoolean(short p0,int p1);
	boolean invokeBoolean(short p0,float p1);
	boolean invokeBoolean(short p0,long p1);
	boolean invokeBoolean(short p0,double p1);
	boolean invokeBoolean(short p0,Object p1);
	boolean invokeBoolean(int p0);
	boolean invokeBoolean(int p0,boolean p1);
	boolean invokeBoolean(int p0,byte p1);
	boolean invokeBoolean(int p0,char p1);
	boolean invokeBoolean(int p0,short p1);
	boolean invokeBoolean(int p0,int p1);
	boolean invokeBoolean(int p0,float p1);
	boolean invokeBoolean(int p0,long p1);
	boolean invokeBoolean(int p0,double p1);
	boolean invokeBoolean(int p0,Object p1);
	boolean invokeBoolean(float p0);
	boolean invokeBoolean(float p0,boolean p1);
	boolean invokeBoolean(float p0,byte p1);
	boolean invokeBoolean(float p0,char p1);
	boolean invokeBoolean(float p0,short p1);
	boolean invokeBoolean(float p0,int p1);
	boolean invokeBoolean(float p0,float p1);
	boolean invokeBoolean(float p0,long p1);
	boolean invokeBoolean(float p0,double p1);
	boolean invokeBoolean(float p0,Object p1);
	boolean invokeBoolean(long p0);
	boolean invokeBoolean(long p0,boolean p1);
	boolean invokeBoolean(long p0,byte p1);
	boolean invokeBoolean(long p0,char p1);
	boolean invokeBoolean(long p0,short p1);
	boolean invokeBoolean(long p0,int p1);
	boolean invokeBoolean(long p0,float p1);
	boolean invokeBoolean(long p0,long p1);
	boolean invokeBoolean(long p0,double p1);
	boolean invokeBoolean(long p0,Object p1);
	boolean invokeBoolean(double p0);
	boolean invokeBoolean(double p0,boolean p1);
	boolean invokeBoolean(double p0,byte p1);
	boolean invokeBoolean(double p0,char p1);
	boolean invokeBoolean(double p0,short p1);
	boolean invokeBoolean(double p0,int p1);
	boolean invokeBoolean(double p0,float p1);
	boolean invokeBoolean(double p0,long p1);
	boolean invokeBoolean(double p0,double p1);
	boolean invokeBoolean(double p0,Object p1);
	boolean invokeBoolean(Object p0);
	boolean invokeBoolean(Object p0,boolean p1);
	boolean invokeBoolean(Object p0,byte p1);
	boolean invokeBoolean(Object p0,char p1);
	boolean invokeBoolean(Object p0,short p1);
	boolean invokeBoolean(Object p0,int p1);
	boolean invokeBoolean(Object p0,float p1);
	boolean invokeBoolean(Object p0,long p1);
	boolean invokeBoolean(Object p0,double p1);
	boolean invokeBoolean(Object p0,Object p1);
	byte invokeByte();
	byte invokeByte(boolean p0);
	byte invokeByte(boolean p0,boolean p1);
	byte invokeByte(boolean p0,byte p1);
	byte invokeByte(boolean p0,char p1);
	byte invokeByte(boolean p0,short p1);
	byte invokeByte(boolean p0,int p1);
	byte invokeByte(boolean p0,float p1);
	byte invokeByte(boolean p0,long p1);
	byte invokeByte(boolean p0,double p1);
	byte invokeByte(boolean p0,Object p1);
	byte invokeByte(byte p0);
	byte invokeByte(byte p0,boolean p1);
	byte invokeByte(byte p0,byte p1);
	byte invokeByte(byte p0,char p1);
	byte invokeByte(byte p0,short p1);
	byte invokeByte(byte p0,int p1);
	byte invokeByte(byte p0,float p1);
	byte invokeByte(byte p0,long p1);
	byte invokeByte(byte p0,double p1);
	byte invokeByte(byte p0,Object p1);
	byte invokeByte(char p0);
	byte invokeByte(char p0,boolean p1);
	byte invokeByte(char p0,byte p1);
	byte invokeByte(char p0,char p1);
	byte invokeByte(char p0,short p1);
	byte invokeByte(char p0,int p1);
	byte invokeByte(char p0,float p1);
	byte invokeByte(char p0,long p1);
	byte invokeByte(char p0,double p1);
	byte invokeByte(char p0,Object p1);
	byte invokeByte(short p0);
	byte invokeByte(short p0,boolean p1);
	byte invokeByte(short p0,byte p1);
	byte invokeByte(short p0,char p1);
	byte invokeByte(short p0,short p1);
	byte invokeByte(short p0,int p1);
	byte invokeByte(short p0,float p1);
	byte invokeByte(short p0,long p1);
	byte invokeByte(short p0,double p1);
	byte invokeByte(short p0,Object p1);
	byte invokeByte(int p0);
	byte invokeByte(int p0,boolean p1);
	byte invokeByte(int p0,byte p1);
	byte invokeByte(int p0,char p1);
	byte invokeByte(int p0,short p1);
	byte invokeByte(int p0,int p1);
	byte invokeByte(int p0,float p1);
	byte invokeByte(int p0,long p1);
	byte invokeByte(int p0,double p1);
	byte invokeByte(int p0,Object p1);
	byte invokeByte(float p0);
	byte invokeByte(float p0,boolean p1);
	byte invokeByte(float p0,byte p1);
	byte invokeByte(float p0,char p1);
	byte invokeByte(float p0,short p1);
	byte invokeByte(float p0,int p1);
	byte invokeByte(float p0,float p1);
	byte invokeByte(float p0,long p1);
	byte invokeByte(float p0,double p1);
	byte invokeByte(float p0,Object p1);
	byte invokeByte(long p0);
	byte invokeByte(long p0,boolean p1);
	byte invokeByte(long p0,byte p1);
	byte invokeByte(long p0,char p1);
	byte invokeByte(long p0,short p1);
	byte invokeByte(long p0,int p1);
	byte invokeByte(long p0,float p1);
	byte invokeByte(long p0,long p1);
	byte invokeByte(long p0,double p1);
	byte invokeByte(long p0,Object p1);
	byte invokeByte(double p0);
	byte invokeByte(double p0,boolean p1);
	byte invokeByte(double p0,byte p1);
	byte invokeByte(double p0,char p1);
	byte invokeByte(double p0,short p1);
	byte invokeByte(double p0,int p1);
	byte invokeByte(double p0,float p1);
	byte invokeByte(double p0,long p1);
	byte invokeByte(double p0,double p1);
	byte invokeByte(double p0,Object p1);
	byte invokeByte(Object p0);
	byte invokeByte(Object p0,boolean p1);
	byte invokeByte(Object p0,byte p1);
	byte invokeByte(Object p0,char p1);
	byte invokeByte(Object p0,short p1);
	byte invokeByte(Object p0,int p1);
	byte invokeByte(Object p0,float p1);
	byte invokeByte(Object p0,long p1);
	byte invokeByte(Object p0,double p1);
	byte invokeByte(Object p0,Object p1);
	char invokeChar();
	char invokeChar(boolean p0);
	char invokeChar(boolean p0,boolean p1);
	char invokeChar(boolean p0,byte p1);
	char invokeChar(boolean p0,char p1);
	char invokeChar(boolean p0,short p1);
	char invokeChar(boolean p0,int p1);
	char invokeChar(boolean p0,float p1);
	char invokeChar(boolean p0,long p1);
	char invokeChar(boolean p0,double p1);
	char invokeChar(boolean p0,Object p1);
	char invokeChar(byte p0);
	char invokeChar(byte p0,boolean p1);
	char invokeChar(byte p0,byte p1);
	char invokeChar(byte p0,char p1);
	char invokeChar(byte p0,short p1);
	char invokeChar(byte p0,int p1);
	char invokeChar(byte p0,float p1);
	char invokeChar(byte p0,long p1);
	char invokeChar(byte p0,double p1);
	char invokeChar(byte p0,Object p1);
	char invokeChar(char p0);
	char invokeChar(char p0,boolean p1);
	char invokeChar(char p0,byte p1);
	char invokeChar(char p0,char p1);
	char invokeChar(char p0,short p1);
	char invokeChar(char p0,int p1);
	char invokeChar(char p0,float p1);
	char invokeChar(char p0,long p1);
	char invokeChar(char p0,double p1);
	char invokeChar(char p0,Object p1);
	char invokeChar(short p0);
	char invokeChar(short p0,boolean p1);
	char invokeChar(short p0,byte p1);
	char invokeChar(short p0,char p1);
	char invokeChar(short p0,short p1);
	char invokeChar(short p0,int p1);
	char invokeChar(short p0,float p1);
	char invokeChar(short p0,long p1);
	char invokeChar(short p0,double p1);
	char invokeChar(short p0,Object p1);
	char invokeChar(int p0);
	char invokeChar(int p0,boolean p1);
	char invokeChar(int p0,byte p1);
	char invokeChar(int p0,char p1);
	char invokeChar(int p0,short p1);
	char invokeChar(int p0,int p1);
	char invokeChar(int p0,float p1);
	char invokeChar(int p0,long p1);
	char invokeChar(int p0,double p1);
	char invokeChar(int p0,Object p1);
	char invokeChar(float p0);
	char invokeChar(float p0,boolean p1);
	char invokeChar(float p0,byte p1);
	char invokeChar(float p0,char p1);
	char invokeChar(float p0,short p1);
	char invokeChar(float p0,int p1);
	char invokeChar(float p0,float p1);
	char invokeChar(float p0,long p1);
	char invokeChar(float p0,double p1);
	char invokeChar(float p0,Object p1);
	char invokeChar(long p0);
	char invokeChar(long p0,boolean p1);
	char invokeChar(long p0,byte p1);
	char invokeChar(long p0,char p1);
	char invokeChar(long p0,short p1);
	char invokeChar(long p0,int p1);
	char invokeChar(long p0,float p1);
	char invokeChar(long p0,long p1);
	char invokeChar(long p0,double p1);
	char invokeChar(long p0,Object p1);
	char invokeChar(double p0);
	char invokeChar(double p0,boolean p1);
	char invokeChar(double p0,byte p1);
	char invokeChar(double p0,char p1);
	char invokeChar(double p0,short p1);
	char invokeChar(double p0,int p1);
	char invokeChar(double p0,float p1);
	char invokeChar(double p0,long p1);
	char invokeChar(double p0,double p1);
	char invokeChar(double p0,Object p1);
	char invokeChar(Object p0);
	char invokeChar(Object p0,boolean p1);
	char invokeChar(Object p0,byte p1);
	char invokeChar(Object p0,char p1);
	char invokeChar(Object p0,short p1);
	char invokeChar(Object p0,int p1);
	char invokeChar(Object p0,float p1);
	char invokeChar(Object p0,long p1);
	char invokeChar(Object p0,double p1);
	char invokeChar(Object p0,Object p1);
	short invokeShort();
	short invokeShort(boolean p0);
	short invokeShort(boolean p0,boolean p1);
	short invokeShort(boolean p0,byte p1);
	short invokeShort(boolean p0,char p1);
	short invokeShort(boolean p0,short p1);
	short invokeShort(boolean p0,int p1);
	short invokeShort(boolean p0,float p1);
	short invokeShort(boolean p0,long p1);
	short invokeShort(boolean p0,double p1);
	short invokeShort(boolean p0,Object p1);
	short invokeShort(byte p0);
	short invokeShort(byte p0,boolean p1);
	short invokeShort(byte p0,byte p1);
	short invokeShort(byte p0,char p1);
	short invokeShort(byte p0,short p1);
	short invokeShort(byte p0,int p1);
	short invokeShort(byte p0,float p1);
	short invokeShort(byte p0,long p1);
	short invokeShort(byte p0,double p1);
	short invokeShort(byte p0,Object p1);
	short invokeShort(char p0);
	short invokeShort(char p0,boolean p1);
	short invokeShort(char p0,byte p1);
	short invokeShort(char p0,char p1);
	short invokeShort(char p0,short p1);
	short invokeShort(char p0,int p1);
	short invokeShort(char p0,float p1);
	short invokeShort(char p0,long p1);
	short invokeShort(char p0,double p1);
	short invokeShort(char p0,Object p1);
	short invokeShort(short p0);
	short invokeShort(short p0,boolean p1);
	short invokeShort(short p0,byte p1);
	short invokeShort(short p0,char p1);
	short invokeShort(short p0,short p1);
	short invokeShort(short p0,int p1);
	short invokeShort(short p0,float p1);
	short invokeShort(short p0,long p1);
	short invokeShort(short p0,double p1);
	short invokeShort(short p0,Object p1);
	short invokeShort(int p0);
	short invokeShort(int p0,boolean p1);
	short invokeShort(int p0,byte p1);
	short invokeShort(int p0,char p1);
	short invokeShort(int p0,short p1);
	short invokeShort(int p0,int p1);
	short invokeShort(int p0,float p1);
	short invokeShort(int p0,long p1);
	short invokeShort(int p0,double p1);
	short invokeShort(int p0,Object p1);
	short invokeShort(float p0);
	short invokeShort(float p0,boolean p1);
	short invokeShort(float p0,byte p1);
	short invokeShort(float p0,char p1);
	short invokeShort(float p0,short p1);
	short invokeShort(float p0,int p1);
	short invokeShort(float p0,float p1);
	short invokeShort(float p0,long p1);
	short invokeShort(float p0,double p1);
	short invokeShort(float p0,Object p1);
	short invokeShort(long p0);
	short invokeShort(long p0,boolean p1);
	short invokeShort(long p0,byte p1);
	short invokeShort(long p0,char p1);
	short invokeShort(long p0,short p1);
	short invokeShort(long p0,int p1);
	short invokeShort(long p0,float p1);
	short invokeShort(long p0,long p1);
	short invokeShort(long p0,double p1);
	short invokeShort(long p0,Object p1);
	short invokeShort(double p0);
	short invokeShort(double p0,boolean p1);
	short invokeShort(double p0,byte p1);
	short invokeShort(double p0,char p1);
	short invokeShort(double p0,short p1);
	short invokeShort(double p0,int p1);
	short invokeShort(double p0,float p1);
	short invokeShort(double p0,long p1);
	short invokeShort(double p0,double p1);
	short invokeShort(double p0,Object p1);
	short invokeShort(Object p0);
	short invokeShort(Object p0,boolean p1);
	short invokeShort(Object p0,byte p1);
	short invokeShort(Object p0,char p1);
	short invokeShort(Object p0,short p1);
	short invokeShort(Object p0,int p1);
	short invokeShort(Object p0,float p1);
	short invokeShort(Object p0,long p1);
	short invokeShort(Object p0,double p1);
	short invokeShort(Object p0,Object p1);
	int invokeInt();
	int invokeInt(boolean p0);
	int invokeInt(boolean p0,boolean p1);
	int invokeInt(boolean p0,byte p1);
	int invokeInt(boolean p0,char p1);
	int invokeInt(boolean p0,short p1);
	int invokeInt(boolean p0,int p1);
	int invokeInt(boolean p0,float p1);
	int invokeInt(boolean p0,long p1);
	int invokeInt(boolean p0,double p1);
	int invokeInt(boolean p0,Object p1);
	int invokeInt(byte p0);
	int invokeInt(byte p0,boolean p1);
	int invokeInt(byte p0,byte p1);
	int invokeInt(byte p0,char p1);
	int invokeInt(byte p0,short p1);
	int invokeInt(byte p0,int p1);
	int invokeInt(byte p0,float p1);
	int invokeInt(byte p0,long p1);
	int invokeInt(byte p0,double p1);
	int invokeInt(byte p0,Object p1);
	int invokeInt(char p0);
	int invokeInt(char p0,boolean p1);
	int invokeInt(char p0,byte p1);
	int invokeInt(char p0,char p1);
	int invokeInt(char p0,short p1);
	int invokeInt(char p0,int p1);
	int invokeInt(char p0,float p1);
	int invokeInt(char p0,long p1);
	int invokeInt(char p0,double p1);
	int invokeInt(char p0,Object p1);
	int invokeInt(short p0);
	int invokeInt(short p0,boolean p1);
	int invokeInt(short p0,byte p1);
	int invokeInt(short p0,char p1);
	int invokeInt(short p0,short p1);
	int invokeInt(short p0,int p1);
	int invokeInt(short p0,float p1);
	int invokeInt(short p0,long p1);
	int invokeInt(short p0,double p1);
	int invokeInt(short p0,Object p1);
	int invokeInt(int p0);
	int invokeInt(int p0,boolean p1);
	int invokeInt(int p0,byte p1);
	int invokeInt(int p0,char p1);
	int invokeInt(int p0,short p1);
	int invokeInt(int p0,int p1);
	int invokeInt(int p0,float p1);
	int invokeInt(int p0,long p1);
	int invokeInt(int p0,double p1);
	int invokeInt(int p0,Object p1);
	int invokeInt(float p0);
	int invokeInt(float p0,boolean p1);
	int invokeInt(float p0,byte p1);
	int invokeInt(float p0,char p1);
	int invokeInt(float p0,short p1);
	int invokeInt(float p0,int p1);
	int invokeInt(float p0,float p1);
	int invokeInt(float p0,long p1);
	int invokeInt(float p0,double p1);
	int invokeInt(float p0,Object p1);
	int invokeInt(long p0);
	int invokeInt(long p0,boolean p1);
	int invokeInt(long p0,byte p1);
	int invokeInt(long p0,char p1);
	int invokeInt(long p0,short p1);
	int invokeInt(long p0,int p1);
	int invokeInt(long p0,float p1);
	int invokeInt(long p0,long p1);
	int invokeInt(long p0,double p1);
	int invokeInt(long p0,Object p1);
	int invokeInt(double p0);
	int invokeInt(double p0,boolean p1);
	int invokeInt(double p0,byte p1);
	int invokeInt(double p0,char p1);
	int invokeInt(double p0,short p1);
	int invokeInt(double p0,int p1);
	int invokeInt(double p0,float p1);
	int invokeInt(double p0,long p1);
	int invokeInt(double p0,double p1);
	int invokeInt(double p0,Object p1);
	int invokeInt(Object p0);
	int invokeInt(Object p0,boolean p1);
	int invokeInt(Object p0,byte p1);
	int invokeInt(Object p0,char p1);
	int invokeInt(Object p0,short p1);
	int invokeInt(Object p0,int p1);
	int invokeInt(Object p0,float p1);
	int invokeInt(Object p0,long p1);
	int invokeInt(Object p0,double p1);
	int invokeInt(Object p0,Object p1);
	float invokeFloat();
	float invokeFloat(boolean p0);
	float invokeFloat(boolean p0,boolean p1);
	float invokeFloat(boolean p0,byte p1);
	float invokeFloat(boolean p0,char p1);
	float invokeFloat(boolean p0,short p1);
	float invokeFloat(boolean p0,int p1);
	float invokeFloat(boolean p0,float p1);
	float invokeFloat(boolean p0,long p1);
	float invokeFloat(boolean p0,double p1);
	float invokeFloat(boolean p0,Object p1);
	float invokeFloat(byte p0);
	float invokeFloat(byte p0,boolean p1);
	float invokeFloat(byte p0,byte p1);
	float invokeFloat(byte p0,char p1);
	float invokeFloat(byte p0,short p1);
	float invokeFloat(byte p0,int p1);
	float invokeFloat(byte p0,float p1);
	float invokeFloat(byte p0,long p1);
	float invokeFloat(byte p0,double p1);
	float invokeFloat(byte p0,Object p1);
	float invokeFloat(char p0);
	float invokeFloat(char p0,boolean p1);
	float invokeFloat(char p0,byte p1);
	float invokeFloat(char p0,char p1);
	float invokeFloat(char p0,short p1);
	float invokeFloat(char p0,int p1);
	float invokeFloat(char p0,float p1);
	float invokeFloat(char p0,long p1);
	float invokeFloat(char p0,double p1);
	float invokeFloat(char p0,Object p1);
	float invokeFloat(short p0);
	float invokeFloat(short p0,boolean p1);
	float invokeFloat(short p0,byte p1);
	float invokeFloat(short p0,char p1);
	float invokeFloat(short p0,short p1);
	float invokeFloat(short p0,int p1);
	float invokeFloat(short p0,float p1);
	float invokeFloat(short p0,long p1);
	float invokeFloat(short p0,double p1);
	float invokeFloat(short p0,Object p1);
	float invokeFloat(int p0);
	float invokeFloat(int p0,boolean p1);
	float invokeFloat(int p0,byte p1);
	float invokeFloat(int p0,char p1);
	float invokeFloat(int p0,short p1);
	float invokeFloat(int p0,int p1);
	float invokeFloat(int p0,float p1);
	float invokeFloat(int p0,long p1);
	float invokeFloat(int p0,double p1);
	float invokeFloat(int p0,Object p1);
	float invokeFloat(float p0);
	float invokeFloat(float p0,boolean p1);
	float invokeFloat(float p0,byte p1);
	float invokeFloat(float p0,char p1);
	float invokeFloat(float p0,short p1);
	float invokeFloat(float p0,int p1);
	float invokeFloat(float p0,float p1);
	float invokeFloat(float p0,long p1);
	float invokeFloat(float p0,double p1);
	float invokeFloat(float p0,Object p1);
	float invokeFloat(long p0);
	float invokeFloat(long p0,boolean p1);
	float invokeFloat(long p0,byte p1);
	float invokeFloat(long p0,char p1);
	float invokeFloat(long p0,short p1);
	float invokeFloat(long p0,int p1);
	float invokeFloat(long p0,float p1);
	float invokeFloat(long p0,long p1);
	float invokeFloat(long p0,double p1);
	float invokeFloat(long p0,Object p1);
	float invokeFloat(double p0);
	float invokeFloat(double p0,boolean p1);
	float invokeFloat(double p0,byte p1);
	float invokeFloat(double p0,char p1);
	float invokeFloat(double p0,short p1);
	float invokeFloat(double p0,int p1);
	float invokeFloat(double p0,float p1);
	float invokeFloat(double p0,long p1);
	float invokeFloat(double p0,double p1);
	float invokeFloat(double p0,Object p1);
	float invokeFloat(Object p0);
	float invokeFloat(Object p0,boolean p1);
	float invokeFloat(Object p0,byte p1);
	float invokeFloat(Object p0,char p1);
	float invokeFloat(Object p0,short p1);
	float invokeFloat(Object p0,int p1);
	float invokeFloat(Object p0,float p1);
	float invokeFloat(Object p0,long p1);
	float invokeFloat(Object p0,double p1);
	float invokeFloat(Object p0,Object p1);
	long invokeLong();
	long invokeLong(boolean p0);
	long invokeLong(boolean p0,boolean p1);
	long invokeLong(boolean p0,byte p1);
	long invokeLong(boolean p0,char p1);
	long invokeLong(boolean p0,short p1);
	long invokeLong(boolean p0,int p1);
	long invokeLong(boolean p0,float p1);
	long invokeLong(boolean p0,long p1);
	long invokeLong(boolean p0,double p1);
	long invokeLong(boolean p0,Object p1);
	long invokeLong(byte p0);
	long invokeLong(byte p0,boolean p1);
	long invokeLong(byte p0,byte p1);
	long invokeLong(byte p0,char p1);
	long invokeLong(byte p0,short p1);
	long invokeLong(byte p0,int p1);
	long invokeLong(byte p0,float p1);
	long invokeLong(byte p0,long p1);
	long invokeLong(byte p0,double p1);
	long invokeLong(byte p0,Object p1);
	long invokeLong(char p0);
	long invokeLong(char p0,boolean p1);
	long invokeLong(char p0,byte p1);
	long invokeLong(char p0,char p1);
	long invokeLong(char p0,short p1);
	long invokeLong(char p0,int p1);
	long invokeLong(char p0,float p1);
	long invokeLong(char p0,long p1);
	long invokeLong(char p0,double p1);
	long invokeLong(char p0,Object p1);
	long invokeLong(short p0);
	long invokeLong(short p0,boolean p1);
	long invokeLong(short p0,byte p1);
	long invokeLong(short p0,char p1);
	long invokeLong(short p0,short p1);
	long invokeLong(short p0,int p1);
	long invokeLong(short p0,float p1);
	long invokeLong(short p0,long p1);
	long invokeLong(short p0,double p1);
	long invokeLong(short p0,Object p1);
	long invokeLong(int p0);
	long invokeLong(int p0,boolean p1);
	long invokeLong(int p0,byte p1);
	long invokeLong(int p0,char p1);
	long invokeLong(int p0,short p1);
	long invokeLong(int p0,int p1);
	long invokeLong(int p0,float p1);
	long invokeLong(int p0,long p1);
	long invokeLong(int p0,double p1);
	long invokeLong(int p0,Object p1);
	long invokeLong(float p0);
	long invokeLong(float p0,boolean p1);
	long invokeLong(float p0,byte p1);
	long invokeLong(float p0,char p1);
	long invokeLong(float p0,short p1);
	long invokeLong(float p0,int p1);
	long invokeLong(float p0,float p1);
	long invokeLong(float p0,long p1);
	long invokeLong(float p0,double p1);
	long invokeLong(float p0,Object p1);
	long invokeLong(long p0);
	long invokeLong(long p0,boolean p1);
	long invokeLong(long p0,byte p1);
	long invokeLong(long p0,char p1);
	long invokeLong(long p0,short p1);
	long invokeLong(long p0,int p1);
	long invokeLong(long p0,float p1);
	long invokeLong(long p0,long p1);
	long invokeLong(long p0,double p1);
	long invokeLong(long p0,Object p1);
	long invokeLong(double p0);
	long invokeLong(double p0,boolean p1);
	long invokeLong(double p0,byte p1);
	long invokeLong(double p0,char p1);
	long invokeLong(double p0,short p1);
	long invokeLong(double p0,int p1);
	long invokeLong(double p0,float p1);
	long invokeLong(double p0,long p1);
	long invokeLong(double p0,double p1);
	long invokeLong(double p0,Object p1);
	long invokeLong(Object p0);
	long invokeLong(Object p0,boolean p1);
	long invokeLong(Object p0,byte p1);
	long invokeLong(Object p0,char p1);
	long invokeLong(Object p0,short p1);
	long invokeLong(Object p0,int p1);
	long invokeLong(Object p0,float p1);
	long invokeLong(Object p0,long p1);
	long invokeLong(Object p0,double p1);
	long invokeLong(Object p0,Object p1);
	double invokeDouble();
	double invokeDouble(boolean p0);
	double invokeDouble(boolean p0,boolean p1);
	double invokeDouble(boolean p0,byte p1);
	double invokeDouble(boolean p0,char p1);
	double invokeDouble(boolean p0,short p1);
	double invokeDouble(boolean p0,int p1);
	double invokeDouble(boolean p0,float p1);
	double invokeDouble(boolean p0,long p1);
	double invokeDouble(boolean p0,double p1);
	double invokeDouble(boolean p0,Object p1);
	double invokeDouble(byte p0);
	double invokeDouble(byte p0,boolean p1);
	double invokeDouble(byte p0,byte p1);
	double invokeDouble(byte p0,char p1);
	double invokeDouble(byte p0,short p1);
	double invokeDouble(byte p0,int p1);
	double invokeDouble(byte p0,float p1);
	double invokeDouble(byte p0,long p1);
	double invokeDouble(byte p0,double p1);
	double invokeDouble(byte p0,Object p1);
	double invokeDouble(char p0);
	double invokeDouble(char p0,boolean p1);
	double invokeDouble(char p0,byte p1);
	double invokeDouble(char p0,char p1);
	double invokeDouble(char p0,short p1);
	double invokeDouble(char p0,int p1);
	double invokeDouble(char p0,float p1);
	double invokeDouble(char p0,long p1);
	double invokeDouble(char p0,double p1);
	double invokeDouble(char p0,Object p1);
	double invokeDouble(short p0);
	double invokeDouble(short p0,boolean p1);
	double invokeDouble(short p0,byte p1);
	double invokeDouble(short p0,char p1);
	double invokeDouble(short p0,short p1);
	double invokeDouble(short p0,int p1);
	double invokeDouble(short p0,float p1);
	double invokeDouble(short p0,long p1);
	double invokeDouble(short p0,double p1);
	double invokeDouble(short p0,Object p1);
	double invokeDouble(int p0);
	double invokeDouble(int p0,boolean p1);
	double invokeDouble(int p0,byte p1);
	double invokeDouble(int p0,char p1);
	double invokeDouble(int p0,short p1);
	double invokeDouble(int p0,int p1);
	double invokeDouble(int p0,float p1);
	double invokeDouble(int p0,long p1);
	double invokeDouble(int p0,double p1);
	double invokeDouble(int p0,Object p1);
	double invokeDouble(float p0);
	double invokeDouble(float p0,boolean p1);
	double invokeDouble(float p0,byte p1);
	double invokeDouble(float p0,char p1);
	double invokeDouble(float p0,short p1);
	double invokeDouble(float p0,int p1);
	double invokeDouble(float p0,float p1);
	double invokeDouble(float p0,long p1);
	double invokeDouble(float p0,double p1);
	double invokeDouble(float p0,Object p1);
	double invokeDouble(long p0);
	double invokeDouble(long p0,boolean p1);
	double invokeDouble(long p0,byte p1);
	double invokeDouble(long p0,char p1);
	double invokeDouble(long p0,short p1);
	double invokeDouble(long p0,int p1);
	double invokeDouble(long p0,float p1);
	double invokeDouble(long p0,long p1);
	double invokeDouble(long p0,double p1);
	double invokeDouble(long p0,Object p1);
	double invokeDouble(double p0);
	double invokeDouble(double p0,boolean p1);
	double invokeDouble(double p0,byte p1);
	double invokeDouble(double p0,char p1);
	double invokeDouble(double p0,short p1);
	double invokeDouble(double p0,int p1);
	double invokeDouble(double p0,float p1);
	double invokeDouble(double p0,long p1);
	double invokeDouble(double p0,double p1);
	double invokeDouble(double p0,Object p1);
	double invokeDouble(Object p0);
	double invokeDouble(Object p0,boolean p1);
	double invokeDouble(Object p0,byte p1);
	double invokeDouble(Object p0,char p1);
	double invokeDouble(Object p0,short p1);
	double invokeDouble(Object p0,int p1);
	double invokeDouble(Object p0,float p1);
	double invokeDouble(Object p0,long p1);
	double invokeDouble(Object p0,double p1);
	double invokeDouble(Object p0,Object p1);
	Object invokeObject();
	Object invokeObject(boolean p0);
	Object invokeObject(boolean p0,boolean p1);
	Object invokeObject(boolean p0,byte p1);
	Object invokeObject(boolean p0,char p1);
	Object invokeObject(boolean p0,short p1);
	Object invokeObject(boolean p0,int p1);
	Object invokeObject(boolean p0,float p1);
	Object invokeObject(boolean p0,long p1);
	Object invokeObject(boolean p0,double p1);
	Object invokeObject(boolean p0,Object p1);
	Object invokeObject(byte p0);
	Object invokeObject(byte p0,boolean p1);
	Object invokeObject(byte p0,byte p1);
	Object invokeObject(byte p0,char p1);
	Object invokeObject(byte p0,short p1);
	Object invokeObject(byte p0,int p1);
	Object invokeObject(byte p0,float p1);
	Object invokeObject(byte p0,long p1);
	Object invokeObject(byte p0,double p1);
	Object invokeObject(byte p0,Object p1);
	Object invokeObject(char p0);
	Object invokeObject(char p0,boolean p1);
	Object invokeObject(char p0,byte p1);
	Object invokeObject(char p0,char p1);
	Object invokeObject(char p0,short p1);
	Object invokeObject(char p0,int p1);
	Object invokeObject(char p0,float p1);
	Object invokeObject(char p0,long p1);
	Object invokeObject(char p0,double p1);
	Object invokeObject(char p0,Object p1);
	Object invokeObject(short p0);
	Object invokeObject(short p0,boolean p1);
	Object invokeObject(short p0,byte p1);
	Object invokeObject(short p0,char p1);
	Object invokeObject(short p0,short p1);
	Object invokeObject(short p0,int p1);
	Object invokeObject(short p0,float p1);
	Object invokeObject(short p0,long p1);
	Object invokeObject(short p0,double p1);
	Object invokeObject(short p0,Object p1);
	Object invokeObject(int p0);
	Object invokeObject(int p0,boolean p1);
	Object invokeObject(int p0,byte p1);
	Object invokeObject(int p0,char p1);
	Object invokeObject(int p0,short p1);
	Object invokeObject(int p0,int p1);
	Object invokeObject(int p0,float p1);
	Object invokeObject(int p0,long p1);
	Object invokeObject(int p0,double p1);
	Object invokeObject(int p0,Object p1);
	Object invokeObject(float p0);
	Object invokeObject(float p0,boolean p1);
	Object invokeObject(float p0,byte p1);
	Object invokeObject(float p0,char p1);
	Object invokeObject(float p0,short p1);
	Object invokeObject(float p0,int p1);
	Object invokeObject(float p0,float p1);
	Object invokeObject(float p0,long p1);
	Object invokeObject(float p0,double p1);
	Object invokeObject(float p0,Object p1);
	Object invokeObject(long p0);
	Object invokeObject(long p0,boolean p1);
	Object invokeObject(long p0,byte p1);
	Object invokeObject(long p0,char p1);
	Object invokeObject(long p0,short p1);
	Object invokeObject(long p0,int p1);
	Object invokeObject(long p0,float p1);
	Object invokeObject(long p0,long p1);
	Object invokeObject(long p0,double p1);
	Object invokeObject(long p0,Object p1);
	Object invokeObject(double p0);
	Object invokeObject(double p0,boolean p1);
	Object invokeObject(double p0,byte p1);
	Object invokeObject(double p0,char p1);
	Object invokeObject(double p0,short p1);
	Object invokeObject(double p0,int p1);
	Object invokeObject(double p0,float p1);
	Object invokeObject(double p0,long p1);
	Object invokeObject(double p0,double p1);
	Object invokeObject(double p0,Object p1);
	Object invokeObject(Object p0);
	Object invokeObject(Object p0,boolean p1);
	Object invokeObject(Object p0,byte p1);
	Object invokeObject(Object p0,char p1);
	Object invokeObject(Object p0,short p1);
	Object invokeObject(Object p0,int p1);
	Object invokeObject(Object p0,float p1);
	Object invokeObject(Object p0,long p1);
	Object invokeObject(Object p0,double p1);
	Object invokeObject(Object p0,Object p1);
}
